apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-home
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-home
  template:
    metadata:
      labels:
        app: web-home
    spec:
      containers:
      - name: web-home
        image: saimonpranta/1-home:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3010
---

apiVersion: v1
kind: Service
metadata:
  name: web-home-service
spec:
  selector:
    app: web-home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3010
  type: ClusterIP
