apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-store
  template:
    metadata:
      labels:
        app: web-store
    spec:
      containers:
      - name: web-store
        image: saimonpranta/10-store
        imagePullPolicy: Always
        ports:
        - containerPort: 3014

---

apiVersion: v1
kind: Service
metadata:
  name: web-store-service
spec:
  selector:
    app: web-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3014
  type: ClusterIP
