apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-wallet
  template:
    metadata:
      labels:
        app: web-wallet
    spec:
      containers:
      - name: web-wallet
        image: saimonpranta/4-wallet
        imagePullPolicy: Always
        ports:
        - containerPort: 3035
---

apiVersion: v1
kind: Service
metadata:
  name: web-wallet-service
spec:
  selector:
    app: web-wallet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3035
  type: ClusterIP
