apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-timeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-timeline
  template:
    metadata:
      labels:
        app: web-timeline
    spec:
      containers:
      - name: web-timeline
        image: saimonpranta/timeline
        imagePullPolicy: Always
        ports:
        - containerPort: 3012
---

apiVersion: v1
kind: Service
metadata:
  name: web-timeline-service
spec:
  selector:
    app: web-timeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3012
  type: ClusterIP
