apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-home
  template:
    metadata:
      labels:
        app: panel-home
    spec:
      containers:
      - name: panel-home
        image: saimonpranta/panel-0-home:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
      nodeSelector:
        kubernetes.io/hostname: k3s-worker-1
---
apiVersion: v1
kind: Service
metadata:
  name: panel-home-service
spec:
  selector:
    app: panel-home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3100
  type: ClusterIP
