apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-store
  template:
    metadata:
      labels:
        app: panel-store
    spec:
      containers:
      - name: panel-store
        image: saimonpranta/31-store:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3131
      nodeSelector:
        kubernetes.io/hostname: k3s-worker-1
---
apiVersion: v1
kind: Service
metadata:
  name: panel-store-service
spec:
  selector:
    app: panel-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3131
  type: ClusterIP
