apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-locker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-locker
  template:
    metadata:
      labels:
        app: panel-locker
    spec:
      containers:
      - name: panel-locker
        image: saimonpranta/34-locker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3134
      nodeSelector:
        kubernetes.io/hostname: k3s-worker-1
---
apiVersion: v1
kind: Service
metadata:
  name: panel-locker-service
spec:
  selector:
    app: panel-locker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3134
  type: ClusterIP
