apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-assistant
  template:
    metadata:
      labels:
        app: panel-assistant
    spec:
      containers:
      - name: panel-assistant
        image: saimonpranta/37-assistant:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3137 
---
apiVersion: v1
kind: Service
metadata:
  name: panel-assistant-service
spec:
  selector:
    app: panel-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3137
  type: ClusterIP
