apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-investments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-investments
  template:
    metadata:
      labels:
        app: panel-investments
    spec:
      containers:
      - name: panel-investments
        image: saimonpranta/38-investments:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3138 
---
apiVersion: v1
kind: Service
metadata:
  name: panel-investments-service
spec:
  selector:
    app: panel-investments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3138
  type: ClusterIP
