apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-jobs
  template:
    metadata:
      labels:
        app: panel-jobs
    spec:
      containers:
      - name: panel-jobs
        image: saimonpranta/41-jobs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3118
      nodeSelector:
        kubernetes.io/hostname: k3s-worker-1
---
apiVersion: v1
kind: Service
metadata:
  name: panel-jobs-service
spec:
  selector:
    app: panel-jobs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3118
  type: ClusterIP
