apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-futures
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-futures
  template:
    metadata:
      labels:
        app: panel-futures
    spec:
      containers:
      - name: panel-futures
        image: saimonpranta/44-futures:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3144
---
apiVersion: v1
kind: Service
metadata:
  name: panel-futures-service
spec:
  selector:
    app: panel-futures
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3144
  type: ClusterIP
