apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-shortener
  template:
    metadata:
      labels:
        app: panel-shortener
    spec:
      containers:
      - name: panel-shortener
        image: saimonpranta/45-shortener:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3145 
---
apiVersion: v1
kind: Service
metadata:
  name: panel-shortener-service
spec:
  selector:
    app: panel-shortener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3145
  type: ClusterIP
