apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel-laboratories
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-laboratories
  template:
    metadata:
      labels:
        app: panel-laboratories
    spec:
      containers:
      - name: panel-laboratories
        image: saimonpranta/46-laboratories:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3146 
---
apiVersion: v1
kind: Service
metadata:
  name: panel-laboratories-service
spec:
  selector:
    app: panel-laboratories
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3146
  type: ClusterIP
