apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
        - name: cloud
          image: saimonpranta/cloud:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_URI
              value: "mongodb://mongodb-service:27017"
          ports:
            - containerPort: 2300
          volumeMounts:
            - mountPath: /var/micple.com/default.imp
              name: www-vol
      volumes:
        - name: www-vol
          persistentVolumeClaim:
            claimName: default-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: cloud-service
spec:
  selector:
    app: cloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2300
  type: ClusterIP
