apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          volumeMounts:
            - mountPath: /data/db
              name: mongo-vol
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: mongo-pvc
    
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
