apiVersion: v1
kind: PersistentVolume
metadata:
  name: insightface-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/insightface-models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insightface-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  volumeName: insightface-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-backend-auth
  template:
    metadata:
      labels:
        app: web-backend-auth
    spec:
      containers:
        - name: web-backend-auth
          image: saimonpranta/auth:latest
          imagePullPolicy: Always

          env:
            - name: VECTOR_DATABASE_URI
              value: "http://qdrant-service:6333"

          ports:
            - containerPort: 2200

          volumeMounts:
            - name: insightface-models
              mountPath: /root/.insightface/models

      volumes:
        - name: insightface-models
          persistentVolumeClaim:
            claimName: insightface-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: web-backend-auth-service
spec:
  selector:
    app: web-backend-auth
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 2200
