apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
spec:
  volumeName: default-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
