apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/micple.com/default.imp
    type: DirectoryOrCreate
